### PR TITLE
Setup lindera tokenizer for ja support ( related with #49 )

### PR DESCRIPTION
**Pull request by miiton**
I implemented my idea for #49.

I apologize first. I was wondering if it would be better to Pull Request to @djKooks' repository or to PR here,
but the difference with the main branch was too big. I decided to send it here.
Is there any problem?

With this, I think that purpose of "using Lindera for Japanese processing" has been achieved.

- As a preliminary step, implement the following from #49
  - Merge main branch.
  - Fixed with @ManyTheFish 's comments.
  - lindera-rs bump to v0.8.1
- As anwer to "How to detect language, Chinese or Japanese?"
  - I implmented with `whatlang::detect_lang()`.
  - Before this commit, used only `whatlang::detect_script()`  to detect "English" or "Other".

| Script           | Language      | Tokenizer |
| ---------------- | ------------- | --------- |
| Script::Mandarin | Language::Cmn | Jieba     |
| Script::Mandarin | Language::Jpn | Lindera   |
| Script::Katakana | Language::Jpn | Lindera   |
| Script::Hiragana | Language::Jpn | Lindera   |

We can probably make a detect with only "Language", but I also left "Script" for backward compatibility.

### Remaining problems.

`関西国際空港限定トートバッグ` was detected as "Japanese", but `関西国際空港` was detected as "Chinese" even though it is "Japanese", because only Mandarin characters are used. This is a whatlang's issue. 
( note: `関西国际空港` is "Chinese")

As for Korean, I found some commits in main branch, so I won't touch on that. 

# Pull Request

## What does this PR do?
Fixes #49

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by ManyTheFish** [comment]
I ran the benchmarks, below are the results:
Capture d’écran 2022-02-21 à 21 19 48

```
default-run/default-run/132B_CHSP1
                        time:   [178.55 us 178.83 us 179.18 us]
                        change: [+0.1870% +0.3638% +0.5399%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 16 outliers among 100 measurements (16.00%)
  2 (2.00%) low severe
  1 (1.00%) low mild
  3 (3.00%) high mild
  10 (10.00%) high severe
default-run/default-run/132B_CHTR1
                        time:   [153.68 us 153.80 us 153.93 us]
                        change: [-2.8321% -2.3203% -1.8517%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe
default-run/default-run/132B_LTEN1
                        time:   [142.13 us 142.34 us 142.55 us]
                        change: [+1332.9% +1341.1% +1348.4%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 5 outliers among 100 measurements (5.00%)
  2 (2.00%) low severe
  1 (1.00%) low mild
  1 (1.00%) high mild
  1 (1.00%) high severe
default-run/default-run/132B_LTFR1
                        time:   [167.17 us 167.49 us 167.82 us]
                        change: [+1530.9% +1536.6% +1540.9%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) low severe
  1 (1.00%) low mild
  3 (3.00%) high mild
default-run/default-run/363B_CHSP2
                        time:   [761.25 us 761.57 us 761.88 us]
                        change: [-0.5849% -0.4049% -0.2411%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe
default-run/default-run/363B_LTEN2
                        time:   [280.57 us 280.84 us 281.13 us]
                        change: [+897.73% +900.83% +903.79%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  1 (1.00%) low severe
  3 (3.00%) high mild
  2 (2.00%) high severe
default-run/default-run/363B_LTFR1
                        time:   [165.01 us 165.59 us 166.38 us]
                        change: [+487.05% +488.57% +490.11%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe
```

As we can see, language detection is impacting significantly Latin tokenization.
Meanwhile, it doesn't impact Chinese tokenization.
I'm thinking of a patch. If I don't manage to avoid language detection for Latin scripts, I'll deactivate it and Japanese tokenization will not work for Chinese scripts 🤔.

**Comment by miiton** [comment]
Thank you for your review :)
I'll check it too.

**Comment by ManyTheFish** [comment]
@miiton, I come back with more benchmarks, I added Japanese text (Chinese + Hiragana) and I found out that Lindera performances are not good, see below (logarithmic scale):
Capture d’écran 2022-02-22 à 12 38 38

I think we forgot something in Lindera initialization, because it seems that the time doesn't depends on the text size. 🤔

**Comment by miiton** [comment]
Thank you for your detailed investigation.
This looks like a problem that Lindera (or another Tokenizer) and whatlang have to solve first 🤔
Or maybe should consider an implementation that reduces performance only in Japanese but does not affect other languages.

**Comment by ManyTheFish** [comment]
Hey @miiton I [patched lindera](https://github.com/lindera-morphology/lindera/pull/143) in order to avoid cloning the lindera instance at each tokenization, @mozuka, the maintainer, has released a v0.10.0 😊

We should update lindera and remove the .clone() in the tokenize method.

**Comment by miiton** [comment]
You really get work done fast 😲

I updated lindera to 0.10.0 and remove `clone()`. 
But I don't know how to benchmark on the current main branch. 😥  I waiting for CONTRIBUTE.md ( #72 ).

**Comment by ManyTheFish** [comment]
Hey @miiton, it's ok, let's merge this I will fix benchmarks in another branch.

Let's merge this, thanks!

bors merge

**Review by ManyTheFish — APPROVED** [review]

**Pull request merged**
